### ISSUE TITLE
List transactions

### ISSUE THREAD

**Issue by nanexcool** [makerdao/simplecoin-explorer#4]
- Recent transaction history
  - Sender
  - Transaction ID prefix
  - Transaction type (most importantly issue/cover/transfer)
    - amount + collateral type (for issue/cover)
    - amount + recipient (for transfer)

**Comment by gbalabasquer** [comment]
@dbrock Question here.
I'm using the Transfer event of ERC20 to get the history of transfer of the coin. However can not find a way to bring the cases of issuing and covering.

The Transfer event is logged as well for issue and cover but in the collateral token and not in the coin itself and there is nothing saved related to the coin itself.

I was wondering if we could add a call to the Transfer event in the issue and cover methods. 
In that case we would have all saved in the same event log and playing with the way to save the data we can differentiate between issue, cover and transfer.
